### ISSUE TITLE
Massive log spam

### ISSUE THREAD

**Issue by aaronhowser1** [CompactMods/CompactCrafting#33] opened 2021-07-04 19:18 UTC
![image](https://user-images.githubusercontent.com/15698722/124396981-99697400-dcd2-11eb-9cb3-cdb205eeae33.png)

This is a debug.log, literally too big for me to upload it. I don't think anyone on the server has even gotten to compact crafting yet.

**Comment by robotgryphon** [comment] 2021-07-04 22:54
Closing as a duplicate of 32.

**Closed as completed by robotgryphon** 2021-07-04 22:54 UTC
